var hasBrokenTemplate = (function(){})()   // boolean   Test for the presence of the Safari template cloning bug
var hasTextareaCloneBug = (function(){})()   // boolean Test for IE10/11 textarea placeholder clone bug
var arrayProto = Array.prototype
var arrayMethods = Object.create(arrayProto)  // 创建一个 array 对象,此对象包含所有 prototype 中的方法
var util = Object.freeze({
  defineReactive: defineReactive,
  set: set,
  del: del,
  hasOwn: hasOwn,
  isLiteral: isLiteral,
  isReserved: isReserved,
  _toString: _toString,
  toNumber: toNumber,
  toBoolean: toBoolean,
  stripQuotes: stripQuotes,
  camelize: camelize,
  hyphenate: hyphenate,
  classify: classify,
  bind: bind,
  toArray: toArray,
  extend: extend,
  isObject: isObject,
  isPlainObject: isPlainObject,
  def: def,
  debounce: _debounce,
  indexOf: indexOf,
  cancellable: cancellable,
  looseEqual: looseEqual,
  isArray: isArray,
  hasProto: hasProto,
  inBrowser: inBrowser,
  devtools: devtools,
  isIE: isIE,
  isIE9: isIE9,
  isAndroid: isAndroid,
  isIos: isIos,
  iosVersionMatch: iosVersionMatch,
  iosVersion: iosVersion,
  hasMutationObserverBug: hasMutationObserverBug,
  get transitionProp () { return transitionProp; },
  get transitionEndEvent () { return transitionEndEvent; },
  get animationProp () { return animationProp; },
  get animationEndEvent () { return animationEndEvent; },
  nextTick: nextTick,
  get _Set () { return _Set; },
  query: query,
  inDoc: inDoc,
  getAttr: getAttr,
  getBindAttr: getBindAttr,
  hasBindAttr: hasBindAttr,
  before: before,
  after: after,
  remove: remove,
  prepend: prepend,
  replace: replace,
  on: on,
  off: off,
  setClass: setClass,
  addClass: addClass,
  removeClass: removeClass,
  extractContent: extractContent,
  trimNode: trimNode,
  isTemplate: isTemplate,
  createAnchor: createAnchor,
  findRef: findRef,
  mapNodeRange: mapNodeRange,
  removeNodeRange: removeNodeRange,
  isFragment: isFragment,
  getOuterHTML: getOuterHTML,
  mergeOptions: mergeOptions,
  resolveAsset: resolveAsset,
  checkComponentAttr: checkComponentAttr,
  commonTagRE: commonTagRE,
  reservedTagRE: reservedTagRE,
  get warn () { return warn; }
});
var uid = 0;
